6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/ORM2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include("student.urls")),
]

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/student/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from student.views import index, add_student, delete_student,edit_student,elective

urlpatterns = [
    path("", index),
    path("add/", add_student),
    re_path("delete/(\d+)", delete_student),
    re_path("edit/(\d+)", edit_student),

    # 选课
    re_path("elective/", elective),


]

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/student/models.py
from django.db import models


# Create your models here.


class Clas(models.Model):
    name = models.CharField(max_length=32, verbose_name="班级名称")

    class Meta:
        db_table = "db_class"




class Course(models.Model):
    title = models.CharField(max_length=32, verbose_name="课程名称")
    credit = models.IntegerField(verbose_name="学分",default=3)
    teacher = models.CharField(max_length=32,null=True)
    classTime = models.CharField(max_length=32,null=True)
    classAddr = models.CharField(max_length=32,null=True)
    # students = models.ManyToManyField("Student",db_table="db_student2course")
    class Meta:
        db_table = "db_course"


    def __str__(self):
        return self.title


class Student(models.Model):

    sex_choices = (
        (0, "女"),
        (1, "男"),
        (2, "保密"),
    )
    name = models.CharField(max_length=32, unique=True, verbose_name="姓名")
    age = models.SmallIntegerField(verbose_name="年龄", default=18)  # 年龄
    sex = models.SmallIntegerField(choices=sex_choices)
    birthday = models.DateField()

    # 一对多的关系:在数据库创建一个关联字段：clas_id
    clas = models.ForeignKey(to="Clas",related_name="student_list",on_delete=models.CASCADE)

    # 一对一的关系：建立关联字段,在数据库中生成关联字段：stu_detail_id
    stu_detail = models.OneToOneField("StudentDetail",related_name="stu",on_delete=models.CASCADE)

    # 多对多的关系：创建第三张关系表
    courses = models.ManyToManyField("Course",related_name="students", db_table="db_student2course")

    class Meta:
        db_table = "db_student"


    def __str__(self):
        return self.name


class StudentDetail(models.Model):
    tel = models.CharField(max_length=11)
    addr = models.CharField(max_length=32)

    class Meta:
        db_table = "db_stu_detail"

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/student/views.py
from django.shortcuts import render, HttpResponse, redirect

# Create your views here.
from .models import Student, StudentDetail, Course, Clas


def index(request):
    # 获取所有的学生数据
    student_list = Student.objects.all()

    return render(request, "student/index.html", {"student_list": student_list})


def add_student(request):
    if request.method == "GET":

        class_list = Clas.objects.all()
        course_list = Course.objects.all()
        return render(request, "student/add_stu.html", {"class_list": class_list, "course_list": course_list})

    else:
        # 获取客户端数据
        # <QueryDict: {'name': ['alvin'], 'age': ['22'], 'sex': ['2'], 'birthday': ['2021-10-26'], 'clas_id': ['8']}>
        print(request.POST)
        # 添加数据到数据库
        # 方式1
        # name = request.POST.get("user")
        # age = request.POST.get("age")
        # sex = request.POST.get("sex")
        # birthday = request.POST.get("birthday")
        # clas_id = request.POST.get("clas_id")
        #
        # Student.objects.create(name=name,age=age,sex=sex,birthday=birthday,clas_id=clas_id)
        # 方式2
        # 前提： 客户端form表单的name值要与models中的字段保持一致
        stu = Student.objects.create(**request.POST.dict())

        return redirect("/student/")


def delete_student(request, del_id):
    student = Student.objects.get(pk=del_id)

    if request.method == "GET":
        return render(request, "student/delete_stu.html", {"student": student})

    else:
        student.delete()
        return redirect("/student/")


def edit_student(request,edit_id):
    edit_stu = Student.objects.get(pk=edit_id)
    if request.method == "GET":

        class_list = Clas.objects.all()
        course_list = Course.objects.all()
        return render(request, "student/edit_stu.html", {"edit_stu": edit_stu, "class_list": class_list,"course_list":course_list})
    else:
        print("request.POST",request.POST)
        course_id_list = request.POST.getlist("course_id_list")
        # 获取客户端数据
        data = request.POST.dict()
        print("data",data)
        # 删除并获取课程id列表
        data.pop("course_id_list")
        # 更新除了多对多以外的数据
        Student.objects.filter(pk=edit_id).update(**data)
        # 多对多关系的重置
        edit_stu.courses.set(course_id_list)
        return redirect("/student/")





def elective(request):

    if request.method == "GET":
        course_list = Course.objects.all()
        return render(request,"student/course.html",{"course_list":course_list})

    else:
        print(request.POST)
        course_id_list =request.POST.getlist("course_id_list")
        stu_id = 14
        stu = Student.objects.get(pk=stu_id)
        stu.courses.set(course_id_list)

        return redirect("/student/")

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/templates/student/add_stu.html
{% extends "student/base.html" %}


{% block content %}
    <section class="forms">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>添加学生</h4>
                </div>
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet consectetur.</p>
                    <form action="/student/add/" method="post">
                        <div class="form-group">
                            <label>姓名</label>
                            <input type="text" placeholder="Name Address" class="form-control" name="name">
                        </div>
                        <div class="form-group">
                            <label>年龄</label>
                            <input type="text" placeholder="Age" class="form-control" name="age">
                        </div>

                        <div class="form-group">
                            <label>性别</label>
                            <select name="sex" id="" class="form-control">
                                <option value="1">男</option>
                                <option value="0">女</option>
                                <option value="2">保密</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>出生日期</label>
                            <input type="date" placeholder="Birth" class="form-control" name="birthday">
                        </div>

                        <div class="form-group">
                            <label>班级</label>
                            <select name="clas_id" id="" class="form-control">
                                {% for class in class_list %}
                                    <option value="{{ class.id }}">{{ class.name }}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group">
                            <input type="submit" value="Signin" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/templates/student/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://www.jq22.com/jquery/bootstrap-4.2.1.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://www.jq22.com/jquery/font-awesome.4.7.0.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="../../static/css/fontastic.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="../../static/css/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="../../static/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="../../static/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="../../static/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="../../static/img/favicon.ico">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <!-- Side Navbar -->
    <nav class="side-navbar">
      <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">
          <!-- User Info-->
          <div class="sidenav-header-inner text-center"><a href="/student/"><img src="../../static/img/avatar-7.jpg" alt="person" class="img-fluid rounded-circle"></a>
            <h2 class="h5">Nathan Andrews</h2><span>Web Developer</span>
          </div>
          <!-- Small Brand information, appears on minimized sidebar-->
          <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong>B</strong><strong class="text-primary">D</strong></a></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
          <h5 class="sidenav-heading">Main</h5>
          <ul id="side-main-menu" class="side-menu list-unstyled">
            <li><a href="/student/"> <i class="icon-home"></i>Home                             </a></li>
            <li><a href="/student/elective/"> <i class="icon-form"></i>选修课程                           </a></li>
            <li><a href="charts.html"> <i class="fa fa-bar-chart"></i>Charts                             </a></li>
            <li><a href="tables.html"> <i class="icon-grid"></i>Tables                             </a></li>
            <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
              <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                <li><a href="#">Page</a></li>
                <li><a href="#">Page</a></li>
                <li><a href="#">Page</a></li>
              </ul>
            </li>
            <li><a href="login.html"> <i class="icon-interface-windows"></i>Login page                             </a></li>
            <li> <a href="#"> <i class="icon-mail"></i>Demo
                <div class="badge badge-warning">6 New</div></a></li>
          </ul>
        </div>

      </div>
    </nav>
    <div class="page">
      <!-- navbar-->
      <header class="header">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
                  <div class="brand-text d-none d-md-inline-block"><span>Bootstrap </span><strong class="text-primary">Dashboard</strong></div></a></div>
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <!-- Notifications dropdown-->
                <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell"></i><span class="badge badge-warning">12</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-envelope"></i>You have 6 new messages </div>
                          <div class="notification-time"><small>4 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                          <div class="notification-time"><small>4 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-upload"></i>Server Rebooted</div>
                          <div class="notification-time"><small>4 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item">
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                          <div class="notification-time"><small>10 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-bell"></i>view all notifications                                            </strong></a></li>
                  </ul>
                </li>
                <!-- Messages dropdown-->
                <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope"></i><span class="badge badge-info">10</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
                        <div class="msg-profile"> <img src="../../static/img/avatar-1.jpg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2019</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
                        <div class="msg-profile"> <img src="../../static/img/avatar-2.jpg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2019</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
                        <div class="msg-profile"> <img src="../../static/img/avatar-3.jpg" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2019</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-envelope"></i>Read all messages    </strong></a></li>
                  </ul>
                </li>
                <!-- Languages dropdown    -->
                <li class="nav-item dropdown"><a id="languages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link language dropdown-toggle"><img src="../../static/img/flags/16/GB.png" alt="English"><span class="d-none d-sm-inline-block">English</span></a>
                  <ul aria-labelledby="languages" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item"> <img src="../../static/img/flags/16/DE.png" alt="English" class="mr-2"><span>German</span></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item"> <img src="../../static/img/flags/16/FR.png" alt="English" class="mr-2"><span>French                                                         </span></a></li>
                  </ul>
                </li>
                <!-- Log out-->
                <li class="nav-item"><a href="login.html" class="nav-link logout"> <span class="d-none d-sm-inline-block">Logout</span><i class="fa fa-sign-out"></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <!-- Updates Section -->
        {% block content %}
        
        {% endblock content%}
     
      <footer class="main-footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <p>Copyright &copy; 2019.Company name All rights reserved.</p>
            </div>
            <div class="col-sm-6 text-right">


            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- JavaScript files-->
    <script src="https://www.jq22.com/jquery/jquery-1.10.2.js"></script>
    <script src="../../static/vendor/popper.js/umd/popper.min.js"> </script>
    <script src="https://www.jq22.com/jquery/bootstrap-4.2.1.js"></script>
    <script src="../../static/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="../../static/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="../../static/vendor/chart.js/Chart.min.js"></script>
    <script src="../../static/vendor/jquery-validation/jquery.validate.min.js"></script>
    <script src="../../static/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="../../static/js/charts-home.js"></script>
    <!-- Main File-->
    <script src="../../static/js/front.js"></script>
  </body>
</html>

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/templates/student/course.html
{% extends "student/base.html" %}


{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4>选课</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                      <form action="" method="post">

                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>选择</th>
                                <th>序号</th>
                                <th>课程名称</th>
                                <th>讲师</th>
                                <th>学分</th>
                                <th>上课时间</th>
                                <th>上课教室</th>
                            </tr>
                            </thead>
                            <tbody>

                                {% for course in course_list %}
                                    <tr>
                                        <td><input type="checkbox" value="{{ course.id }}" name="course_id_list"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ course.title }}</td>
                                        <td>{{ course.teacher }}</td>
                                        <td>{{ course.credit }}</td>
                                        <td>{{ course.classTime }}</td>
                                        <td>{{ course.classAddr }}</td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                        <p><input type="submit" class="btn btn-info pull-right"></p>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/templates/student/delete_stu.html
{% extends "student/base.html" %}




{% block content %}
 <div class="col-md-10">
              <div class="card">
                <div class="card-header d-flex align-items-center">
                  <h4>Horizontal Form</h4>
                </div>
                <div class="card-body">
                  <p>
                        <table class="table table-striped table-hover">

                            <tbody>

                                <tr>

                                    <td>{{ student.name }}</td>
                                    <td>{{ student.age }}</td>
                                    <td>{{ student.get_sex_display }}</td>
                                    <td>{{ student.birthday|date:'Y-m-d' }}</td>
                                    <td>{{ student.clas.name }}</td>
                                    <td>
                                        {% for course in student.courses.all %}
                                            <button class="btn btn-sm btn-success">{{ course.title }}</button>
                                        {% endfor %}
                                    </td>


                                </tr>

                            </tbody>
                        </table>
                  </p>
                  <form action="" method="post" class="form-horizontal">

                    <div class="form-group row">
                      <div class="col-sm-10 offset-sm-2">
                        <input type="submit" value="确认删除" class="btn btn-danger pull-right">
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/templates/student/edit_stu.html
{% extends "student/base.html" %}



{% block content %}
    <section class="forms">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>编辑学生</h4>
                </div>
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet consectetur.</p>
                    <form action="" method="post">
                        <div class="form-group">
                            <label>姓名</label>
                            <input type="text" value="{{ edit_stu.name }}" placeholder="Name Address"
                                   class="form-control" name="name">
                        </div>
                        <div class="form-group">
                            <label>年龄</label>
                            <input type="text" value="{{ edit_stu.age }}" placeholder="Age" class="form-control"
                                   name="age">
                        </div>

                        <div class="form-group">
                            <label>性别</label>
                            <select name="sex" id="" class="form-control">

                                {% if edit_stu.sex == 0 %}

                                    <option value="1">男</option>
                                    <option value="0" selected>女</option>
                                    <option value="2">保密</option>

                                {% elif edit_stu.sex == 1 %}
                                    <option value="1" selected>男</option>
                                    <option value="0">女</option>
                                    <option value="2">保密</option>
                                {% else %}

                                    <option value="1">男</option>
                                    <option value="0">女</option>
                                    <option value="2" selected>保密</option>

                                {% endif %}


                            </select>
                        </div>

                        <div class="form-group">
                            <label>出生日期</label>
                            <input type="date" value="{{ edit_stu.birthday|date:'Y-m-d' }}" placeholder="Birth"
                                   class="form-control" name="birthday">
                        </div>

                        <div class="form-group">
                            <label>班级</label>
                            <select name="clas_id" id="" class="form-control">
                                {% for class in class_list %}
                                    {% if class == edit_stu.clas %}
                                        <option selected value="{{ class.id }}">{{ class.name }}</option>
                                    {% else %}
                                        <option value="{{ class.id }}">{{ class.name }}</option>
                                    {% endif %}

                                {% endfor %}
                            </select>
                        </div>


                       <div class="form-group">
                            <label>选修课程</label>
                            <select name="course_id_list" id="" class="form-control" multiple size="5">
                                {% for course in course_list %}

                                    {% if course in edit_stu.courses.all %}
                                         <option selected value="{{ course.id }}">{{ course.title }}</option>
                                    {% else %}
                                         <option class="" value="{{ course.id }}">{{ course.title }}</option>
                                    {% endif %}

                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Signin" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

6Django/Django开发基础V2.0/Django课程代码/选课系统代码/ORM2/templates/student/index.html
{% extends "student/base.html" %}




{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4>学生管理</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <p><a class="btn btn-info" href="/student/add/">添加学生</a></p>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>姓名</th>
                                <th>年龄</th>
                                <th>性别</th>
                                <th>生日</th>
                                <th>班级</th>
                                <th>选修课程</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for student in student_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ student.name }}</td>
                                    <td>{{ student.age }}</td>
                                    <td>{{ student.get_sex_display }}</td>
                                    <td>{{ student.birthday|date:'Y-m-d' }}</td>
                                    <td>{{ student.clas.name }}</td>
                                    <td>
                                        {% for course in student.courses.all %}
                                            <button class="btn btn-sm btn-success">{{ course.title }}</button>
                                        {% endfor %}
                                    </td>

                                    <td>
                                        <a class="btn-sm btn-warning" href="/student/edit/{{ student.pk }}">编辑</a>
                                        <a class="btn-sm btn-danger" href="/student/delete/{{ student.pk }}">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}